version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"