package com.jonichi.common.constant

const val TAG_ADD_HABIT_NAVIGATION = "TAG_ADD_HABIT_NAVIGATION"
const val TAG_BACK_ARROW = "TAG_BACK_ARROW"
const val TAG_FORM_INPUT_FIELD = "TAG_FORM_INPUT_FIELD"
const val TAG_TIME_DIALOG = "TAG_TIME_DIALOG"