package com.jonichi.common.constant

const val TAG_ADD_HABIT_NAVIGATION = "TAG_ADD_HABIT_NAVIGATION"
const val TAG_BACK_ARROW = "TAG_BACK_ARROW"
const val TAG_FORM_INPUT_FIELD = "TAG_FORM_INPUT_FIELD"
const val TAG_TIME_INPUT = "TAG_TIME_INPUT"
const val TAG_BUTTON_CANCEL = "TAG_BUTTON_CANCEL"
const val TAG_BUTTON_CONFIRM = "TAG_BUTTON_CONFIRM"
const val TAG_STRICT_BADGE = "TAG_STRICT_BADGE"
